homework10/app_homework10/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "app_homework10"

urlpatterns = [
    path("", views.quotes, name='quotes'),
    path("quotes/", views.quotes, name='quotes'),
    path("authors/", views.authors, name='authors'),
    path("authors/<int:author_id>", views.author_card, name='author_card'),
    path("author_add", views.author_add, name='author_add'),
    path("quote_add", views.quote_add, name='quote_add'),
]

homework10/homework10/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("app_homework10.urls")),
    path("users/", include("users.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

homework10/users/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from .forms import LoginForm
from .views import RegisterView

app_name = "users"

urlpatterns = [
    path("signup/", RegisterView.as_view(), name='register'),
    path("signin/", LoginView.as_view(template_name='users/signin.html', authentication_form=LoginForm,
                                      redirect_authenticated_user=True), name='login'),
    path("logout/", LogoutView.as_view(template_name="users/logout.html"), name='logout'),
]

homework10/app_homework10/models.py
from django.db import models
from django.contrib.auth.models import User


class Author(models.Model):
    fullname = models.CharField(max_length=150)
    birthday = models.CharField(max_length=50)
    birth_place = models.CharField(max_length=150)
    bio = models.CharField(max_length=15000)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)

    def __str__(self):
        return f'{self.fullname}'


class Quote(models.Model):
    quote = models.CharField(max_length=250)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, default=1)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)

homework10/users/models.py
from django.db import models

# Create your models here.

homework10/app_homework10/forms.py
from django.forms import ModelForm, CharField, TextInput, ModelChoiceField, Textarea

from .models import Author, Quote


class AuthorForm(ModelForm):
    fullname = CharField(max_length=150, required=True, widget=TextInput(attrs={"class": "form-control"}))
    birthday = CharField(max_length=50, required=True, widget=TextInput(attrs={"class": "form-control"}))
    birth_place = CharField(max_length=150, required=True, widget=TextInput(attrs={"class": "form-control"}))
    bio = CharField(max_length=15000, required=True, widget=Textarea(attrs={"class": "form-control"}))

    class Meta:
        model = Author
        fields = ['fullname', 'birthday', 'birth_place', 'bio']


class QuoteForm(ModelForm):
    quote = CharField(max_length=250, required=True, widget=TextInput(attrs={"class": "form-control"}))
    author = ModelChoiceField(queryset=Author.objects.all().order_by('fullname'), required=True, empty_label=None)

    class Meta:
        model = Quote
        fields = ['quote', 'author']

homework10/users/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.forms import CharField, TextInput, EmailField, EmailInput, PasswordInput


class RegisterForm(UserCreationForm):
    username = CharField(max_length=100, required=True, widget=TextInput(attrs={"class": "form-control"}))
    first_name = CharField(max_length=150, required=False, widget=TextInput(attrs={"class": "form-control"}))
    last_name = CharField(max_length=150, required=False, widget=TextInput(attrs={"class": "form-control"}))
    email = EmailField(max_length=150, required=True, widget=EmailInput(attrs={"class": "form-control"}))
    password1 = CharField(max_length=12, min_length=5, required=True,
                          widget=PasswordInput(attrs={"class": "form-control"}))
    password2 = CharField(max_length=12, min_length=5, required=True,
                          widget=PasswordInput(attrs={"class": "form-control"}))

    class Meta:
        model = User
        fields = ("username", "first_name", "last_name", "email", "password1", "password2")


class LoginForm(AuthenticationForm):
    username = CharField(max_length=100, required=True, widget=TextInput(attrs={"class": "form-control"}))
    password = CharField(max_length=12, min_length=5, required=True,
                          widget=PasswordInput(attrs={"class": "form-control"}))

    class Meta:
        model = User
        fields = ("username", "password")

homework10/app_homework10/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.conf import settings


from .forms import AuthorForm, QuoteForm
from .models import Author, Quote


# Create your views here.
def main(request):
    return render(request, 'app_homework10/index.html', context={"title": "Homework 10"})


@login_required
def author_add(request):
    form = AuthorForm(instance=Author())
    if request.method == "POST":
        form = AuthorForm(request.POST, request.FILES, instance=Author())
        if form.is_valid():
            author = form.save(commit=False)
            author.user = request.user
            author.save()
            author_name = form.cleaned_data["fullname"]
            messages.success(request, f'Congrats new Author {author_name} was added!')
            return redirect(to="app_homework10:authors")
    return render(request, 'app_homework10/author_add.html', context={"title": "Homework 10", "form": form})


@login_required
def quote_add(request):
    form = QuoteForm(instance=Quote())
    if request.method == "POST":
        form = QuoteForm(request.POST, request.FILES, instance=Quote())
        if form.is_valid():
            quote = form.save(commit=False)
            quote.user = request.user
            quote.save()
            messages.success(request, f'Congrats new Quote was added!')
            return redirect(to="app_homework10:quotes")
    return render(request, 'app_homework10/quote_add.html', context={"title": "Homework 10", "form": form})


def quotes(request):
    quotes_all = Quote.objects.filter().all()
    return render(request, 'app_homework10/quote.html',
                  context={"title": "Homework 10", "quotes": quotes_all, "media": settings.MEDIA_URL})


def authors(request):
    authors_all = Author.objects.filter().all()
    return render(request, 'app_homework10/author.html',
                  context={"title": "Homework 10", "authors": authors_all, "media": settings.MEDIA_URL})


def author_card(request, author_id):
    author = Author.objects.filter(pk=author_id).all()
    return render(request, 'app_homework10/author.html',
                  context={"title": "Homework 10", "authors": author, "media": settings.MEDIA_URL})

homework10/users/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib import messages

from .forms import RegisterForm


class RegisterView(View):
    form_class = RegisterForm
    template_name = "users/signup.html"

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect(to="app_homework10:root")
        return super(RegisterView, self).dispatch(request, * args, ** kwargs)

    def get(self, request):
        return render(request, self.template_name, {"form": self.form_class})

    def post(self, request):
        form = self.form_class(request.POST)
        print(form)
        if form.is_valid():
            form.save()
            username = form.cleaned_data["username"]
            messages.success(request, f'Congrats {username}! Your account was created!')
            return redirect(to="users:login")

        return render(request, self.template_name, {"form": form})

homework10/app_homework10/templates/app_homework10/author.html
{% extends "app_homework10/base.html" %}

{% block content %}
{% if messages %}
{% for message in messages %}
<div {% if message.tags %} class="alert alert-{{message.tags}}" {% endif %} role="alert">
    {{message}}
</div>
{% endfor %}
{% endif %}
<div class="row">
    {% for author in authors %}
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">{{author.fullname}}</h5>
            <h6 class="card-subtitle mb-2 text-body-secondary">{{author.birthday}}</h6>
            <h6 class="card-subtitle mb-2 text-body-secondary">{{author.birth_place}}</h6>
            <p class="card-text">{{author.bio}}</p>
            <p class="card-text"><small class="text-body-secondary">This bio was added by: {{author.user.username}}</small></p>
          </div>
        </div>
      {% endfor %}

</div>
{% endblock %}

homework10/app_homework10/templates/app_homework10/author_add.html
{% extends "app_homework10/base.html" %}

{% block content %}
<h1>Create new author page</h1>
{% if messages %}
{% for message in messages %}
<div {% if message.tags %} class="alert alert-{{message.tags}}" {% endif %} role="alert">
    {{message}}
</div>
{% endfor %}
{% endif %}
<form action="{% url 'app_homework10:author_add' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mb-3">
        <label class="form-label">Full Name</label>
        {{form.fullname}}
    </div>
    <div class="mb-3">
        <label class="form-label">Birthday</label>
        {{form.birthday}}
    </div>
    <div class="mb-3">
        <label class="form-label">Birth place</label>
        {{form.birth_place}}
    </div>
    <div class="mb-3">
        <label class="form-label">Biography</label>
        {{form.bio}}
    </div>
    <button type="submit" class="btn btn-primary">Create new author</button>
</form>
{% endblock %}

homework10/app_homework10/templates/app_homework10/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <title>{{title}}</title>
</head>
<body>
<div class="container">
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="/">Quotes</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/authors">Authors</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="/author_add">Add Author</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/quote_add">Add Quote</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:logout' %}">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}">SignIn</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:register' %}">SignUp</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    {% block content %}
    {% endblock %}
</div>
</body>
</html>

homework10/app_homework10/templates/app_homework10/index.html
{% extends "app_homework10/base.html" %}

{% block content %}
<h1>Quotes</h1>
{% if messages %}
{% for message in messages %}
<div {% if message.tags %} class="alert alert-{{message.tags}}" {% endif %} role="alert">
    {{message}}
</div>
{% endfor %}
{% endif %}
<div class="row">
    {% for quote in quotes %}
    <div class="card">
      <div class="card-body">
        <blockquote class="blockquote mb-0">
          <p>{{quote.quote}}</p>
          <footer class="blockquote-footer"><cite title="Author">{{quote.author.fullname}}</cite></footer>
        </blockquote>
      </div>
    </div>
    {% endfor %}

</div>
{% endblock %}

homework10/app_homework10/templates/app_homework10/quote.html
{% extends "app_homework10/base.html" %}

{% block content %}
<h1>Quotes</h1>
{% if messages %}
{% for message in messages %}
<div {% if message.tags %} class="alert alert-{{message.tags}}" {% endif %} role="alert">
    {{message}}
</div>
{% endfor %}
{% endif %}
<div class="row">
    {% for quote in quotes %}
    <div class="card">
      <div class="card-body">
        <blockquote class="blockquote mb-0">
          <p>{{quote.quote}}</p>
          <footer class="blockquote-footer"><cite title="Author"><a href="/authors/{{quote.author.id}}" class="card-link">{{quote.author.fullname}}</a></cite></footer>
        </blockquote>
      </div>
    </div>
    {% endfor %}

</div>
{% endblock %}

homework10/app_homework10/templates/app_homework10/quote_add.html
{% extends "app_homework10/base.html" %}

{% block content %}
<h1>Create new qoute</h1>
{% if messages %}
{% for message in messages %}
<div {% if message.tags %} class="alert alert-{{message.tags}}" {% endif %} role="alert">
    {{message}}
</div>
{% endfor %}
{% endif %}

<form action="{% url 'app_homework10:quote_add' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mb-3">
        <label class="form-label">Quote</label>
        {{form.quote}}
    </div>
    <div class="mb-3">
        <label class="form-label">Author</label>
        {{form.author}}
    </div>
    <button type="submit" class="btn btn-primary">Save new quote</button>
</form>
{% endblock %}

homework10/users/templates/users/logout.html
{% extends "app_homework10/base.html" %}

{% block content %}
<h1>See you again!</h1>
{% endblock %}

homework10/users/templates/users/signin.html
{% extends "app_homework10/base.html" %}

{% block content %}
<h1>SignUp</h1>

<!-- Виводимо Flash сповіщення-->
{% if messages %}
{% for message in messages %}
<div {% if message.tags %} class="alert alert-{{message.tags}}" {% endif %} role="alert">
    {{message}}
</div>
{% endfor %}
{% endif %}

<!--Обробляємо помилки форми які не відносяться до полів -->
{% if form.errors %}
<div class="alert alert-danger" role="alert">
  {{ form.non_field_errors}}
</div>
{% endif %}

<form method="post">
    {% csrf_token %}
    <div class="form-row">
        <div class="mb-3">
            <label class="form-label">Username</label>
            {{form.username}}
        </div>
        <span>{{form.errors.username}}</span>
    </div>
    <div class="form-row">
        <div class="mb-3">
            <label class="form-label">Password</label>
            {{form.password}}
        </div>
        <span>{{form.errors.password}}</span>
    </div>
    <button type="submit" class="btn btn-primary">Sing In</button>
</form>
{% endblock %}

homework10/users/templates/users/signup.html
{% extends "app_homework10/base.html" %}

{% block content %}
<h1>SignUp</h1>
<form method="post">
    {% csrf_token %}
    <div class="form-row">
        <div class="mb-3">
            <label class="form-label">Username</label>
            {{form.username}}
        </div>
        <span>{{form.errors.username}}</span>
    </div>
    <div class="form-row">
        <div class="mb-3">
            <label class="form-label">First Name</label>
            {{form.first_name}}
        </div>
        <span>{{form.errors.first_name}}</span>
    </div>
    <div class="form-row">
        <div class="mb-3">
            <label class="form-label">Last Name</label>
            {{form.last_name}}
        </div>
        <span>{{form.errors.last_name}}</span>
    </div>
    <div class="form-row">
        <div class="mb-3">
            <label class="form-label">Email</label>
            {{form.email}}
        </div>
        <span>{{form.errors.email}}</span>
    </div>
    <div class="form-row">
        <div class="mb-3">
            <label class="form-label">Password</label>
            {{form.password1}}
        </div>
        <span>{{form.errors.password1}}</span>
    </div>
    <div class="form-row">
        <div class="mb-3">
            <label class="form-label">Confirm password</label>
            {{form.password2}}
        </div>
        <span>{{form.errors.password2}}</span>
    </div>
    <button type="submit" class="btn btn-primary">Sing Up</button>
</form>
{% endblock %}